name: incomeandexpense
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
# for bottom naviation bar
  animated_bottom_navigation_bar: ^1.2.1
# for splash screen
  another_flutter_splash_screen: ^1.1.5
  awesome_snackbar_content: ^0.1.3
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
# for charts to incomes and expenses
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
# for container clip paths
  flutter_custom_clippers: ^2.1.0
# for nice icons
  flutter_iconly: ^1.0.2
# for responsive app
  flutter_screenutil: ^5.9.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
# for nice icons also
  iconsax: ^0.0.8
  image_picker: ^1.0.4
# for date formatter 
  intl: ^0.18.1
# for nice icons also
  ionicons: ^0.2.2
# for lottie files
  lottie: ^2.6.0
# for url lancher how ever the website and my whats and github ....
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/
  output_path: lib/Helpers/
  filename: images.dart
  field_prefix: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter/Inter-Thin.ttf
        weight: 100
      - asset: fonts/Inter/Inter-ExtraLight.ttf
        weight: 200
      - asset: fonts/Inter/Inter-Light.ttf
        weight: 300
      - asset: fonts/Inter/Inter-Regular.ttf
        weight: 400
      - asset: fonts/Inter/Inter-Medium.ttf
        weight: 500
      - asset: fonts/Inter/Inter-SemiBold.ttf
        weight: 600
      - asset: fonts/Inter/Inter-Bold.ttf
        weight: 700
      - asset: fonts/Inter/Inter-ExtraBold.ttf
        weight: 800
      - asset: fonts/Inter/Inter-Black.ttf
        weight: 900
